defmodule AcceptanceHarness.SchemaDiagramArtifacts do
  @moduledoc false

  @marker_prefix "acceptance-schema-source-sha256"
  @marker_regex ~r/<!-- #{@marker_prefix}: [0-9a-f]{64} -->\n?/

  def current?(svg, dot) when is_binary(svg) and is_binary(dot) do
    valid_svg?(svg) and String.contains?(svg, marker(dot))
  end

  def stamp(svg, dot) when is_binary(svg) and is_binary(dot) do
    svg = Regex.replace(@marker_regex, svg, "")
    marker = marker(dot)

    case String.split(svg, "\n", parts: 2) do
      ["<?xml" <> _rest = declaration, body] ->
        declaration <> "\n" <> marker <> "\n" <> body

      _other ->
        marker <> "\n" <> svg
    end
  end

  def renderer_version(svg) when is_binary(svg) do
    case Regex.run(~r/Generated by graphviz version ([^\n]+)\n/, svg) do
      [_, version] -> String.trim(version)
      _other -> nil
    end
  end

  defp marker(dot), do: "<!-- #{@marker_prefix}: #{source_hash(dot)} -->"

  defp valid_svg?(svg) do
    svg
    |> String.trim_leading()
    |> then(&(String.starts_with?(&1, "<?xml") or String.starts_with?(&1, "<svg")))
  end

  defp source_hash(dot) do
    :sha256
    |> :crypto.hash(dot)
    |> Base.encode16(case: :lower)
  end
end
