defmodule AcceptanceHarness.SchemaDiagramArtifactsTest do
  use ExUnit.Case, async: true

  alias AcceptanceHarness.SchemaDiagramArtifacts

  @svg """
  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
  <svg><text>schema</text></svg>
  """

  test "stamps an SVG with its DOT source hash" do
    stamped = SchemaDiagramArtifacts.stamp(@svg, "digraph Schema { users; }")

    assert stamped =~
             ~r/^<\?xml[^\n]+\n<!-- acceptance-schema-source-sha256: [0-9a-f]{64} -->\n/

    assert SchemaDiagramArtifacts.current?(stamped, "digraph Schema { users; }")
  end

  test "detects an SVG whose DOT source changed" do
    stamped = SchemaDiagramArtifacts.stamp(@svg, "digraph Schema { users; }")

    refute SchemaDiagramArtifacts.current?(stamped, "digraph Schema { users; sessions; }")
    refute SchemaDiagramArtifacts.current?(@svg, "digraph Schema { users; }")
  end

  test "rejects a matching source stamp when diagnostics precede the SVG" do
    dot = "digraph Schema { users; }"
    invalid = "Warning: non-ASCII width fallback\n" <> SchemaDiagramArtifacts.stamp(@svg, dot)

    refute SchemaDiagramArtifacts.current?(invalid, dot)
  end

  test "restamping replaces the prior source hash without duplicating metadata" do
    restamped =
      @svg
      |> SchemaDiagramArtifacts.stamp("digraph Schema { users; }")
      |> SchemaDiagramArtifacts.stamp("digraph Schema { users; sessions; }")

    assert length(Regex.scan(~r/acceptance-schema-source-sha256/, restamped)) == 1
    assert SchemaDiagramArtifacts.current?(restamped, "digraph Schema { users; sessions; }")
  end

  test "reads the Graphviz renderer version from generated SVG metadata" do
    old_svg = "<!-- Generated by graphviz version 2.43.0 (0)\n -->"
    new_svg = "<!-- Generated by graphviz version 12.2.0 (20241103.1931)\n -->"

    assert SchemaDiagramArtifacts.renderer_version(old_svg) == "2.43.0 (0)"
    assert SchemaDiagramArtifacts.renderer_version(new_svg) == "12.2.0 (20241103.1931)"
    assert SchemaDiagramArtifacts.renderer_version("<svg></svg>") == nil
  end
end
